app = "citizenx-pinning-service"
primary_region = "fra"

[build]
  builder = "heroku/builder:22"
  buildpacks = ["heroku/nodejs"]
  [build.args]
    NPM_CONFIG_PRODUCTION = "true"

[env]
  PORT = "10000"
  NODE_ENV = "production"

[mounts]
  source = "gun_data"
  destination = "/var/data"

[http_service]
  internal_port = 10000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"

[processes]
  app = "npm start"
